### ISSUE TITLE
Listen to 'invalid' event on a model

### ISSUE THREAD

**Issue by kanejoe** [magalhas/backbone-react-component#53]
hi, I wonder if you could give me an example of how to listen to a backbone model's 'invalid' event within the component using this library. many thanks.

**Comment by magalhas** [comment]
I wasn't aware of that event. Is it triggered by models when they don't pass the validate function?

**Comment by kanejoe** [comment]
that's it exactly - when a model's validation fails this event is triggered.

**Comment by magalhas** [comment]
For the time being the mixin is not listening to this event. We can easily add it.

**Comment by kanejoe** [comment]
that would actually be very useful, thanks

**Comment by magalhas** [comment]
It'll be on the next release (can't promise when).

**Comment by magalhas** [comment]
@kanejoe the fix is already available on the master branch. I think I'll be able to release a beta version including it by the weekend but feel free to try it out.

Basically `@state.isInvalid` is set to true if the event is triggered, and false when a request is being made. Probably this ain't enough, because there probably is some more information passed through the event. I plan to check this out when I write an unit test for it, but please feel free to create a PR with any changes around #L202

**Comment by kanejoe** [comment]
super.  Will have a look and revert
